### ISSUE TITLE
玩家登录报错 1.14.4 spigot 

### ISSUE THREAD

**Issue by lovemercer** [Arasple/LiteChat#1]
[02:03:03] [User Authenticator #1/INFO]: UUID of player Rookie is b2e9c5ef-d176-329f-a3c1-86cc82c0d59d
[02:03:06] [Server thread/WARN]: java.lang.NullPointerException
[02:03:06] [Server thread/WARN]:        at java.io.StringReader.<init>(Unknown Source)
[02:03:06] [Server thread/WARN]:        at io.izzel.taboolib.internal.gson.JsonParser.parse(JsonParser.java:45)
[02:03:06] [Server thread/WARN]:        at io.izzel.taboolib.util.serialize.TSerializer.read(TSerializer.java:27)
[02:03:06] [Server thread/WARN]:        at io.izzel.taboolib.util.serialize.TSerializable.read(TSerializable.java:20)
[02:03:06] [Server thread/WARN]:        at me.arasple.mc.litechat.data.DataHandler.initFor(DataHandler.java:67)
[02:03:06] [Server thread/WARN]:        at me.arasple.mc.litechat.listeners.ListenerPlayerJoin.onJoin(ListenerPlayerJoin.java:22)
[02:03:06] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:03:06] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[02:03:06] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[02:03:06] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[02:03:06] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316)
[02:03:06] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:03:06] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529)
[02:03:06] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514)
[02:03:06] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:173)
[02:03:06] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:154)
[02:03:06] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:53)
[02:03:06] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:220)
[02:03:06] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129)
[02:03:06] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1091)
[02:03:06] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393)
[02:03:06] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970)
[02:03:06] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815)
[02:03:06] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by Arasple** [comment]
Fixed in v1.33
