### ISSUE TITLE
一个加载上的问题 

### ISSUE THREAD

**Issue by bushuaichen** [Arasple/LiteChat#3]
`Using default channel type
[19:22:36] [Server thread/WARN]: java.lang.ClassCastException: Cannot cast jdk.internal.loader.ClassLoaders$AppClassLoader to java.net.URLClassLoader

[19:22:36] [Server thread/WARN]: 	at java.base/java.lang.Class.cast(Class.java:3604)

[19:22:36] [Server thread/WARN]: 	at me.arasple.mc.litechat.LiteChatPlugin$Loader.addPath(LiteChatPlugin.java:542)

[19:22:36] [Server thread/WARN]: 	at me.arasple.mc.litechat.LiteChatPlugin.init(LiteChatPlugin.java:411)

[19:22:36] [Server thread/WARN]: 	at me.arasple.mc.litechat.LiteChatPlugin.<clinit>(LiteChatPlugin.java:65)

[19:22:36] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)

[19:22:36] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:416)

[19:22:36] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59)

[19:22:36] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135)

[19:22:36] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334)

[19:22:36] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:253)

[19:22:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:350)

[19:22:36] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:202)

[19:22:36] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775)

[19:22:36] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:830)
`
希望可以支持java13

**Comment by Arasple** [comment]
do not support java13
